name: Waka Readme

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_API_URL: ${{ vars.WAKATIME_API_URL || 'https://wakatime.com/api/v1/' }}
          GH_TOKEN: ${{ github.token }}
